name: "Feat Request"
description: "기능 추가 또는 개선"
title: "[Feat] "

body:
  - type: input
    id: "feature_type"
    attributes:
      label: "🛠 종류"
      placeholder: "작업의 종류를 간략히 설명해 주세요. 예) feat, fix, chore 등"

  - type: textarea
    id: "feature_description"
    attributes:
      label: "📄 설명 (필수)"
      placeholder: |
        기능 또는 개선 사항에 대해 자세히 작성해 주세요.
        예: 유저 목록 조회를 위한 API 구현

  - type: checkboxes
    id: "to_do"
    attributes:
      label: "✅ To do"
      description: "필요한 작업 항목을 체크박스 형태로 작성해 주세요."
      options:
        - label: "엔티티 생성: DB 테이블에 매핑되는 엔티티 클래스를 생성합니다."
        - label: "DTO 설계: 데이터 전송을 위한 Request 및 Response DTO를 설계합니다."
        - label: "서비스 구현: 비즈니스 로직을 처리할 서비스 클래스를 구현합니다."
        - label: "컨트롤러 작성: API 엔드포인트를 제공하는 컨트롤러를 작성합니다."
        - label: "테스트 코드 작성: 서비스 및 컨트롤러에 대한 단위 테스트 및 통합 테스트를 작성합니다."
        - label: "문서화: API 스펙 문서(Swagger 또는 Postman)를 작성합니다."
        - label: "코드 리뷰: PR을 생성하고 팀원들과 코드 리뷰를 진행합니다."
        - label: "배포: 애플리케이션을 배포 환경에 배포합니다."

  - type: input
    id: "reference_links"
    attributes:
      label: "🔗 참고 자료"
      placeholder: "관련 문서나 링크가 있다면 작성해 주세요."
